# Sample setup macro with no visualization

/run/verbose 1
/tracking/verbose 0
/hits/verbose 0
/grdm/verbose 0

/control/execute /opt/Validation/Generate/macReference/hkfd_withod.mac

/WCSim/PMTQEMethod SensitiveDetector_Only

#turn on or off the collection efficiency
/WCSim/PMTCollEff on

# command to choose save or not save the pi0 info 07/03/10 (XQ)
/WCSim/SavePi0 false

#choose the Trigger & Digitizer type (and options)
/DAQ/Digitizer SKI
/DAQ/Trigger NoTrigger

#grab the other DAQ options (thresholds, timing windows, etc.)
/control/execute /opt/Validation/Generate/macReference/daq/daq.mac

/control/execute /opt/Validation/Generate/macReference/dark/darktank0.mac
/control/execute /opt/Validation/Generate/macReference/dark/darkmpmt0.mac
/control/execute /opt/Validation/Generate/macReference/dark/darkod0.mac

/control/execute /opt/Validation/Generate/macReference/physics/gun500MeVemODbarrelIn_startY.mac

/Tracking/fractionOpticalPhotonsToDraw 0.0

/WCSimIO/SaveRooTracker 0

## change the name of the output root file, default = wcsim.root
/WCSimIO/RootFile wcsim_hkfdcomplete_SensitiveDetector_Only_NoTrigger_gun500MeVemODbarrelIn_startY_dark0_n200.root

## set a timer running on WCSimRunAction
#/WCSimIO/Timer false

/WCSim/random/seed 20230628
/run/beamOn 200
#exit
